### ISSUE TITLE
Using Cake.AzureCLI in DevOps 

### ISSUE THREAD

**Issue by mandalorianbob** [lprichar/Cake.AzureCli#2]
I was recommended Cake.AzureCLI because I'm trying to download a pfx in my Cake.Frosting build runner. It works locally great, but wow, trying to use it in Azure DevOps has proven to be more difficult than I would like.

Basically, the problem that I'm running into is that I haven't figured out how to use a Service Connection to log into Azure.

Right now it looks like what I'd have to do is create a secret in the service principal and then store that in a secret in the Pipelines Library and then use it to login. But if I'm going to do all that, I might as well just bring in the PFX in the YAML instead of in Cake.

It looks like based on how you described creating this library that you probably don't have much (if any) custom logic in it. But I was wondering if you had any ideas for how to use an existing Service Connection when using Azure CLI

**Comment by JuergenRB** [comment]
You should get a token with the command [Get-AzAccessToken](https://docs.microsoft.com/en-us/powershell/module/az.accounts/get-azaccesstoken?view=azps-6.6.0) when you call it in the [AzurePowershell ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops) task. 

Then you only need to pass the token to tasks that cannot call the service connection directly.

**Comment by mandalorianbob** [comment]
Hrm, so I tried this, but I wasn't able to figure out how to use the access token I got to log back in to Azure.

I got the User Id and the Token from Get-AzAccessToken, but then for a normal Powershell Task, how do I log in to Azure with that?

**Comment by JuergenRB** [comment]
If you have the following task, the AzAccessToken should be in the AccessToken variable and usable in other tasks inside the pipeline. 

```YML
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'YOUR_AZURE_SERVICE_CONNECTION'
    ScriptType: 'InlineScript'
    Inline: |
      $accessToken = Get-AzAccessToken 
      echo "##vso[task.setvariable variable=accesstoken;]$($accessToken.Token)"
    azurePowerShellVersion: 'LatestVersion'
```

**Comment by mandalorianbob** [comment]
Yes, I did something similar. However, when you say "usable in other tasks" that's the part that I was having difficulty with. I wanted to use it in a Powershell so that the Cake instance I'm running is in an authenticated az cli environment
I thought maybe service principal with the Token's UserId and Token ...
```YAML
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host $env:AZ_USER_ID
      az login --service-principal --username $env:AZ_USER_ID --password $env:AZ_ACCESS_TOKEN --tenant [TENANT_ID]
    pwsh: true
  env: 
    AZ_ACCESS_TOKEN: $(AzureAccessTask.az_access_token)
    AZ_USER_ID: $(AzureAccessTask.az_uid)
```
But that just got me "Invalid client secret is provided."

I see that I can use the Access Token in REST calls, but since I'm using Azure CLI in Cake, I was hoping to use something that would assist with that. 

Thanks for the assistance!
